/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */
/*

   Derby - File org.apache.derby.impl.sql.compile.sqlgrammar.jj

   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to you under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

*/

package org.apache.derby.impl.sql.compile;

public interface SQLParserConstants {

  int EOF = 0;
  int NOT_D = 16;
  int NOT_DE = 19;
  int NOT_DER = 22;
  int NOT_DERB = 25;
  int NOT_DERBY = 28;
  int NOT_DERBYDASH = 31;
  int NOT_DERBYDASHP = 34;
  int NOT_DERBYDASHPR = 37;
  int NOT_DERBYDASHPRO = 40;
  int NOT_DERBYDASHPROP = 43;
  int NOT_DERBYDASHPROPE = 46;
  int NOT_DERBYDASHPROPER = 49;
  int NOT_DERBYDASHPROPERT = 52;
  int NOT_DERBYDASHPROPERTI = 55;
  int NOT_DERBYDASHPROPERTIE = 58;
  int DERBYDASHPROPERTIES = 59;
  int NOT_PROPERTIES = 62;
  int SINGLE_LINE_SQLCOMMENT = 63;
  int CHECK_PROPERTIES = 64;
  int ADD = 65;
  int ALL = 66;
  int ALLOCATE = 67;
  int ALTER = 68;
  int AND = 69;
  int ANY = 70;
  int ARE = 71;
  int AS = 72;
  int ASC = 73;
  int ASSERTION = 74;
  int AT = 75;
  int AUTHORIZATION = 76;
  int AVG = 77;
  int BEGIN = 78;
  int BETWEEN = 79;
  int BINARY = 80;
  int BIT = 81;
  int BOTH = 82;
  int BY = 83;
  int CASCADE = 84;
  int CASCADED = 85;
  int CASE = 86;
  int CAST = 87;
  int CHAR = 88;
  int CHARACTER = 89;
  int CHARACTER_LENGTH = 90;
  int CHECK = 91;
  int CLOSE = 92;
  int COALESCE = 93;
  int COLLATE = 94;
  int COLLATION = 95;
  int COLUMN = 96;
  int COMMIT = 97;
  int CONNECT = 98;
  int CONNECTION = 99;
  int CONSTRAINT = 100;
  int CONSTRAINTS = 101;
  int CONTINUE = 102;
  int CONVERT = 103;
  int CORRESPONDING = 104;
  int COUNT = 105;
  int CREATE = 106;
  int CURRENT = 107;
  int CURRENT_DATE = 108;
  int CURRENT_TIME = 109;
  int CURRENT_TIMESTAMP = 110;
  int CURRENT_USER = 111;
  int CURSOR = 112;
  int D = 113;
  int DEALLOCATE = 114;
  int DEC = 115;
  int DECIMAL = 116;
  int DECLARE = 117;
  int _DEFAULT = 118;
  int DEFERRABLE = 119;
  int DEFERRED = 120;
  int DELETE = 121;
  int DESC = 122;
  int DESCRIBE = 123;
  int DIAGNOSTICS = 124;
  int DISCONNECT = 125;
  int DISTINCT = 126;
  int DOUBLE = 127;
  int DROP = 128;
  int ELSE = 129;
  int END = 130;
  int ENDEXEC = 131;
  int ESCAPE = 132;
  int EXCEPT = 133;
  int EXCEPTION = 134;
  int EXEC = 135;
  int EXECUTE = 136;
  int EXISTS = 137;
  int EXTERNAL = 138;
  int FALSE = 139;
  int FETCH = 140;
  int FIRST = 141;
  int FLOAT = 142;
  int FOR = 143;
  int FOREIGN = 144;
  int FOUND = 145;
  int FROM = 146;
  int FULL = 147;
  int FUNCTION = 148;
  int GET = 149;
  int GLOBAL = 150;
  int GO = 151;
  int GOTO = 152;
  int GRANT = 153;
  int GROUP = 154;
  int HAVING = 155;
  int HOUR = 156;
  int IDENTITY = 157;
  int IMMEDIATE = 158;
  int IN = 159;
  int INDICATOR = 160;
  int INITIALLY = 161;
  int INNER = 162;
  int INPUT = 163;
  int INSENSITIVE = 164;
  int INSERT = 165;
  int INT = 166;
  int INTEGER = 167;
  int INTERSECT = 168;
  int INTO = 169;
  int IS = 170;
  int ISOLATION = 171;
  int JOIN = 172;
  int KEY = 173;
  int LAST = 174;
  int LEADING = 175;
  int LEFT = 176;
  int LIKE = 177;
  int LOWER = 178;
  int MATCH = 179;
  int MAX = 180;
  int MIN = 181;
  int MINUTE = 182;
  int MODULE = 183;
  int NATIONAL = 184;
  int NATURAL = 185;
  int NCHAR = 186;
  int NEXT = 187;
  int NO = 188;
  int NOT = 189;
  int NULL = 190;
  int NULLIF = 191;
  int NUMERIC = 192;
  int OF = 193;
  int ON = 194;
  int ONLY = 195;
  int OPEN = 196;
  int OPTION = 197;
  int OR = 198;
  int ORDER = 199;
  int OUTER = 200;
  int OUTPUT = 201;
  int OVERLAPS = 202;
  int PAD = 203;
  int PARTIAL = 204;
  int PREPARE = 205;
  int PRESERVE = 206;
  int PRIMARY = 207;
  int PRIOR = 208;
  int PRIVILEGES = 209;
  int PROCEDURE = 210;
  int PUBLIC = 211;
  int READ = 212;
  int REAL = 213;
  int REFERENCES = 214;
  int RELATIVE = 215;
  int RESTRICT = 216;
  int REVOKE = 217;
  int RIGHT = 218;
  int ROLLBACK = 219;
  int ROWS = 220;
  int SCHEMA = 221;
  int SCROLL = 222;
  int SECOND = 223;
  int SELECT = 224;
  int SESSION_USER = 225;
  int SET = 226;
  int SMALLINT = 227;
  int SOME = 228;
  int SPACE = 229;
  int SQL = 230;
  int SQLCODE = 231;
  int SQLERROR = 232;
  int SQLSTATE = 233;
  int SUBSTRING = 234;
  int SUM = 235;
  int SYSTEM_USER = 236;
  int T = 237;
  int TABLE = 238;
  int TEMPORARY = 239;
  int TIMEZONE_HOUR = 240;
  int TIMEZONE_MINUTE = 241;
  int TO = 242;
  int TRANSACTION = 243;
  int TRANSLATE = 244;
  int TRANSLATION = 245;
  int TRAILING = 246;
  int TRIM = 247;
  int TRUE = 248;
  int TS = 249;
  int UNION = 250;
  int UNIQUE = 251;
  int UNKNOWN = 252;
  int UPDATE = 253;
  int UPPER = 254;
  int USER = 255;
  int USING = 256;
  int VALUE = 257;
  int VALUES = 258;
  int VARBINARY = 259;
  int VARCHAR = 260;
  int VARYING = 261;
  int VIEW = 262;
  int WHENEVER = 263;
  int WHERE = 264;
  int WITH = 265;
  int WORK = 266;
  int WRITE = 267;
  int YEAR = 268;
  int ABS = 269;
  int ABSVAL = 270;
  int ACTION = 271;
  int ALWAYS = 272;
  int BLOB = 273;
  int C = 274;
  int CALLED = 275;
  int CLOB = 276;
  int COBOL = 277;
  int COMMITTED = 278;
  int CONCAT = 279;
  int CONTAINS = 280;
  int DATA = 281;
  int DATE = 282;
  int DAY = 283;
  int DEFINER = 284;
  int DYNAMIC = 285;
  int FORTRAN = 286;
  int GENERATED = 287;
  int IDENTITY_VAL_LOCAL = 288;
  int INCREMENT = 289;
  int INITIAL = 290;
  int INOUT = 291;
  int INTERVAL = 292;
  int INVOKER = 293;
  int LANGUAGE = 294;
  int LARGE = 295;
  int LENGTH = 296;
  int LEVEL = 297;
  int LOCKS = 298;
  int LOCKSIZE = 299;
  int LOGGED = 300;
  int MOD = 301;
  int MODIFIES = 302;
  int MODIFY = 303;
  int MONTH = 304;
  int _MORE = 305;
  int MUMPS = 306;
  int NAME = 307;
  int NCLOB = 308;
  int NULLABLE = 309;
  int NULLS = 310;
  int NUMBER = 311;
  int OBJECT = 312;
  int PASCAL = 313;
  int PLI = 314;
  int PRECISION = 315;
  int RELEASE = 316;
  int REPEATABLE = 317;
  int RESTART = 318;
  int RETURNS = 319;
  int ROW = 320;
  int SAVEPOINT = 321;
  int SCALE = 322;
  int SECURITY = 323;
  int SERIALIZABLE = 324;
  int SQL_TSI_FRAC_SECOND = 325;
  int SQL_TSI_SECOND = 326;
  int SQL_TSI_MINUTE = 327;
  int SQL_TSI_HOUR = 328;
  int SQL_TSI_DAY = 329;
  int SQL_TSI_WEEK = 330;
  int SQL_TSI_MONTH = 331;
  int SQL_TSI_QUARTER = 332;
  int SQL_TSI_YEAR = 333;
  int START = 334;
  int STATEMENT = 335;
  int SYNONYM = 336;
  int THEN = 337;
  int TIME = 338;
  int TIMESTAMP = 339;
  int TIMESTAMPADD = 340;
  int TIMESTAMPDIFF = 341;
  int TRUNCATE = 342;
  int TYPE = 343;
  int UNCOMMITTED = 344;
  int USAGE = 345;
  int WHEN = 346;
  int BOOLEAN = 347;
  int CALL = 348;
  int CURDATE = 349;
  int CURRENT_ROLE = 350;
  int CURTIME = 351;
  int DATABASE = 352;
  int GET_CURRENT_CONNECTION = 353;
  int EXPLAIN = 354;
  int LONGINT = 355;
  int LONG = 356;
  int LTRIM = 357;
  int NONE = 358;
  int OVER = 359;
  int ROLE = 360;
  int ROW_NUMBER = 361;
  int RTRIM = 362;
  int SUBSTR = 363;
  int XML = 364;
  int XMLEXISTS = 365;
  int XMLPARSE = 366;
  int XMLQUERY = 367;
  int XMLSERIALIZE = 368;
  int AFTER = 369;
  int BEFORE = 370;
  int CLASS = 371;
  int COMPRESS = 372;
  int CONTENT = 373;
  int CS = 374;
  int CURSORS = 375;
  int DB2SQL = 376;
  int DERBY_JDBC_RESULT_SET = 377;
  int DIRTY = 378;
  int DOCUMENT = 379;
  int EACH = 380;
  int EMPTY = 381;
  int EXCLUSIVE = 382;
  int FN = 383;
  int INDEX = 384;
  int JAVA = 385;
  int LCASE = 386;
  int LOCATE = 387;
  int LOCK = 388;
  int MESSAGE_LOCALE = 389;
  int METHOD = 390;
  int MODE = 391;
  int NEW = 392;
  int NEW_TABLE = 393;
  int NVARCHAR = 394;
  int OJ = 395;
  int OFF = 396;
  int OLD = 397;
  int OLD_TABLE = 398;
  int OUT = 399;
  int PARAMETER = 400;
  int PASSING = 401;
  int PROPERTIES = 402;
  int READS = 403;
  int REF = 404;
  int REFERENCING = 405;
  int RENAME = 406;
  int RESET = 407;
  int RESULT = 408;
  int RETAIN = 409;
  int RETURNING = 410;
  int RR = 411;
  int RS = 412;
  int SEQUENCE = 413;
  int SEQUENTIAL = 414;
  int SETS = 415;
  int SHARE = 416;
  int SQLID = 417;
  int SPECIFIC = 418;
  int SQRT = 419;
  int STABILITY = 420;
  int STRIP = 421;
  int STYLE = 422;
  int TRIGGER = 423;
  int UCASE = 424;
  int UR = 425;
  int WHITESPACE = 426;
  int DOUBLE_QUOTE = 427;
  int PERCENT = 428;
  int AMPERSAND = 429;
  int QUOTE = 430;
  int LEFT_BRACE = 431;
  int RIGHT_BRACE = 432;
  int LEFT_PAREN = 433;
  int RIGHT_PAREN = 434;
  int ASTERISK = 435;
  int PLUS_SIGN = 436;
  int COMMA = 437;
  int MINUS_SIGN = 438;
  int PERIOD = 439;
  int SOLIDUS = 440;
  int COLON = 441;
  int DOUBLE_COLON = 442;
  int SEMICOLON = 443;
  int LESS_THAN_OPERATOR = 444;
  int LESS_THAN_OR_EQUALS_OPERATOR = 445;
  int EQUALS_OPERATOR = 446;
  int NOT_EQUALS_OPERATOR = 447;
  int NOT_EQUALS_OPERATOR2 = 448;
  int GREATER_THAN_OPERATOR = 449;
  int GREATER_THAN_OR_EQUALS_OPERATOR = 450;
  int QUESTION_MARK = 451;
  int UNDERSCORE = 452;
  int VERTICAL_BAR = 453;
  int LEFT_BRACKET = 454;
  int RIGHT_BRACKET = 455;
  int CONCATENATION_OPERATOR = 456;
  int FIELD_REFERENCE = 457;
  int IDENTIFIER = 458;
  int K = 459;
  int M = 460;
  int G = 461;
  int LETTER = 462;
  int DIGIT = 463;
  int DELIMITED_IDENTIFIER = 464;
  int EXACT_NUMERIC = 465;
  int UINT = 466;
  int LENGTH_MODIFIER = 467;
  int STRING = 468;
  int HEX_STRING = 469;
  int APPROXIMATE_NUMERIC = 470;
  int INTERVAL_LITERAL = 471;
  int INTERVAL_STRING = 472;
  int INTERVAL_QUALIFIER = 473;
  int SINGLE_DATETIME_FIELD = 474;
  int START_FIELD = 475;
  int END_FIELD = 476;
  int NON_SECOND_DATETIME_FIELD = 477;
  int YEAR_MONTH_LITERAL = 478;
  int DAY_TIME_LITERAL = 479;
  int DAY_TIME_INTERVAL = 480;
  int SECONDS_VALUE = 481;
  int TIME_INTERVAL = 482;

  int DEFAULT = 0;
  int IN_BRACKETED_COMMENT = 1;
  int IN_NESTED_BRACKETED_COMMENT = 2;
  int IN_COMMENT = 3;
  int LOOKFOR_DE = 4;
  int LOOKFOR_DER = 5;
  int LOOKFOR_DERB = 6;
  int LOOKFOR_DERBY = 7;
  int LOOKFOR_DERBYDASH = 8;
  int LOOKFOR_DERBYDASHP = 9;
  int LOOKFOR_DERBYDASHPR = 10;
  int LOOKFOR_DERBYDASHPRO = 11;
  int LOOKFOR_DERBYDASHPROP = 12;
  int LOOKFOR_DERBYDASHPROPE = 13;
  int LOOKFOR_DERBYDASHPROPER = 14;
  int LOOKFOR_DERBYDASHPROPERT = 15;
  int LOOKFOR_DERBYDASHPROPERTI = 16;
  int LOOKFOR_DERBYDASHPROPERTIE = 17;
  int LOOKFOR_DERBYDASHPROPERTIES = 18;
  int IT_IS_NOT_DERBYPROPERTIES_COMMENT = 19;
  int PROPERTIES_LIST = 20;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\"--\"",
    "\" \"",
    "\"\\t\"",
    "\"D\"",
    "<token of kind 15>",
    "<NOT_D>",
    "\"E\"",
    "<token of kind 18>",
    "<NOT_DE>",
    "\"R\"",
    "<token of kind 21>",
    "<NOT_DER>",
    "\"B\"",
    "<token of kind 24>",
    "<NOT_DERB>",
    "\"Y\"",
    "<token of kind 27>",
    "<NOT_DERBY>",
    "\"-\"",
    "<token of kind 30>",
    "<NOT_DERBYDASH>",
    "\"P\"",
    "<token of kind 33>",
    "<NOT_DERBYDASHP>",
    "\"R\"",
    "<token of kind 36>",
    "<NOT_DERBYDASHPR>",
    "\"O\"",
    "<token of kind 39>",
    "<NOT_DERBYDASHPRO>",
    "\"P\"",
    "<token of kind 42>",
    "<NOT_DERBYDASHPROP>",
    "\"E\"",
    "<token of kind 45>",
    "<NOT_DERBYDASHPROPE>",
    "\"R\"",
    "<token of kind 48>",
    "<NOT_DERBYDASHPROPER>",
    "\"T\"",
    "<token of kind 51>",
    "<NOT_DERBYDASHPROPERT>",
    "\"I\"",
    "<token of kind 54>",
    "<NOT_DERBYDASHPROPERTI>",
    "\"E\"",
    "<token of kind 57>",
    "<NOT_DERBYDASHPROPERTIE>",
    "\"DERBYDASHPROPERTIES\"",
    "\"S\"",
    "<token of kind 61>",
    "<NOT_PROPERTIES>",
    "<SINGLE_LINE_SQLCOMMENT>",
    "<CHECK_PROPERTIES>",
    "\"add\"",
    "\"all\"",
    "\"allocate\"",
    "\"alter\"",
    "\"and\"",
    "\"any\"",
    "\"are\"",
    "\"as\"",
    "\"asc\"",
    "\"assertion\"",
    "\"at\"",
    "\"authorization\"",
    "\"avg\"",
    "\"begin\"",
    "\"between\"",
    "\"binary\"",
    "\"bit\"",
    "\"both\"",
    "\"by\"",
    "\"cascade\"",
    "\"cascaded\"",
    "\"case\"",
    "\"cast\"",
    "\"char\"",
    "\"character\"",
    "\"character_length\"",
    "\"check\"",
    "\"close\"",
    "\"coalesce\"",
    "\"collate\"",
    "\"collation\"",
    "\"column\"",
    "\"commit\"",
    "\"connect\"",
    "\"connection\"",
    "\"constraint\"",
    "\"constraints\"",
    "\"continue\"",
    "\"convert\"",
    "\"corresponding\"",
    "\"count\"",
    "\"create\"",
    "\"current\"",
    "\"current_date\"",
    "\"current_time\"",
    "\"current_timestamp\"",
    "\"current_user\"",
    "\"cursor\"",
    "\"d\"",
    "\"deallocate\"",
    "\"dec\"",
    "\"decimal\"",
    "\"declare\"",
    "\"default\"",
    "\"deferrable\"",
    "\"deferred\"",
    "\"delete\"",
    "\"desc\"",
    "\"describe\"",
    "\"diagnostics\"",
    "\"disconnect\"",
    "\"distinct\"",
    "\"double\"",
    "\"drop\"",
    "\"else\"",
    "\"end\"",
    "\"end-exec\"",
    "\"escape\"",
    "\"except\"",
    "\"exception\"",
    "\"exec\"",
    "\"execute\"",
    "\"exists\"",
    "\"external\"",
    "\"false\"",
    "\"fetch\"",
    "\"first\"",
    "\"float\"",
    "\"for\"",
    "\"foreign\"",
    "\"found\"",
    "\"from\"",
    "\"full\"",
    "\"function\"",
    "\"get\"",
    "\"global\"",
    "\"go\"",
    "\"goto\"",
    "\"grant\"",
    "\"group\"",
    "\"having\"",
    "\"hour\"",
    "\"identity\"",
    "\"immediate\"",
    "\"in\"",
    "\"indicator\"",
    "\"initially\"",
    "\"inner\"",
    "\"input\"",
    "\"insensitive\"",
    "\"insert\"",
    "\"int\"",
    "\"integer\"",
    "\"intersect\"",
    "\"into\"",
    "\"is\"",
    "\"isolation\"",
    "\"join\"",
    "\"key\"",
    "\"last\"",
    "\"leading\"",
    "\"left\"",
    "\"like\"",
    "\"lower\"",
    "\"match\"",
    "\"max\"",
    "\"min\"",
    "\"minute\"",
    "\"module\"",
    "\"national\"",
    "\"natural\"",
    "\"nchar\"",
    "\"next\"",
    "\"no\"",
    "\"not\"",
    "\"null\"",
    "\"nullif\"",
    "\"numeric\"",
    "\"of\"",
    "\"on\"",
    "\"only\"",
    "\"open\"",
    "\"option\"",
    "\"or\"",
    "\"order\"",
    "\"outer\"",
    "\"output\"",
    "\"overlaps\"",
    "\"pad\"",
    "\"partial\"",
    "\"prepare\"",
    "\"preserve\"",
    "\"primary\"",
    "\"prior\"",
    "\"privileges\"",
    "\"procedure\"",
    "\"public\"",
    "\"read\"",
    "\"real\"",
    "\"references\"",
    "\"relative\"",
    "\"restrict\"",
    "\"revoke\"",
    "\"right\"",
    "\"rollback\"",
    "\"rows\"",
    "\"schema\"",
    "\"scroll\"",
    "\"second\"",
    "\"select\"",
    "\"session_user\"",
    "\"set\"",
    "\"smallint\"",
    "\"some\"",
    "\"space\"",
    "\"sql\"",
    "\"sqlcode\"",
    "\"sqlerror\"",
    "\"sqlstate\"",
    "\"substring\"",
    "\"sum\"",
    "\"system_user\"",
    "\"t\"",
    "\"table\"",
    "\"temporary\"",
    "\"timezone_hour\"",
    "\"timezone_minute\"",
    "\"to\"",
    "\"transaction\"",
    "\"translate\"",
    "\"translation\"",
    "\"trailing\"",
    "\"trim\"",
    "\"true\"",
    "\"ts\"",
    "\"union\"",
    "\"unique\"",
    "\"unknown\"",
    "\"update\"",
    "\"upper\"",
    "\"user\"",
    "\"using\"",
    "\"value\"",
    "\"values\"",
    "\"varbinary\"",
    "\"varchar\"",
    "\"varying\"",
    "\"view\"",
    "\"whenever\"",
    "\"where\"",
    "\"with\"",
    "\"work\"",
    "\"write\"",
    "\"year\"",
    "\"abs\"",
    "\"absval\"",
    "\"action\"",
    "\"always\"",
    "\"blob\"",
    "\"c\"",
    "\"called\"",
    "\"clob\"",
    "\"cobol\"",
    "\"committed\"",
    "\"concat\"",
    "\"contains\"",
    "\"data\"",
    "\"date\"",
    "\"day\"",
    "\"definer\"",
    "\"dynamic\"",
    "\"fortran\"",
    "\"generated\"",
    "\"identity_val_local\"",
    "\"increment\"",
    "\"initial\"",
    "\"inout\"",
    "\"interval\"",
    "\"invoker\"",
    "\"language\"",
    "\"large\"",
    "\"length\"",
    "\"level\"",
    "\"locks\"",
    "\"locksize\"",
    "\"logged\"",
    "\"mod\"",
    "\"modifies\"",
    "\"modify\"",
    "\"month\"",
    "\"more\"",
    "\"mumps\"",
    "\"name\"",
    "\"nclob\"",
    "\"nullable\"",
    "\"nulls\"",
    "\"number\"",
    "\"object\"",
    "\"pascal\"",
    "\"pli\"",
    "\"precision\"",
    "\"release\"",
    "\"repeatable\"",
    "\"restart\"",
    "\"returns\"",
    "\"row\"",
    "\"savepoint\"",
    "\"scale\"",
    "\"security\"",
    "\"serializable\"",
    "\"sql_tsi_frac_second\"",
    "\"sql_tsi_second\"",
    "\"sql_tsi_minute\"",
    "\"sql_tsi_hour\"",
    "\"sql_tsi_day\"",
    "\"sql_tsi_week\"",
    "\"sql_tsi_month\"",
    "\"sql_tsi_quarter\"",
    "\"sql_tsi_year\"",
    "\"start\"",
    "\"statement\"",
    "\"synonym\"",
    "\"then\"",
    "\"time\"",
    "\"timestamp\"",
    "\"timestampadd\"",
    "\"timestampdiff\"",
    "\"truncate\"",
    "\"type\"",
    "\"uncommitted\"",
    "\"usage\"",
    "\"when\"",
    "\"boolean\"",
    "\"call\"",
    "\"curdate\"",
    "\"current_role\"",
    "\"curtime\"",
    "\"database\"",
    "\"getCurrentConnection\"",
    "\"explain\"",
    "\"bigint\"",
    "\"long\"",
    "\"ltrim\"",
    "\"none\"",
    "\"over\"",
    "\"role\"",
    "\"row_number\"",
    "\"rtrim\"",
    "\"substr\"",
    "\"xml\"",
    "\"xmlexists\"",
    "\"xmlparse\"",
    "\"xmlquery\"",
    "\"xmlserialize\"",
    "\"after\"",
    "\"before\"",
    "\"class\"",
    "\"compress\"",
    "\"content\"",
    "\"cs\"",
    "\"cursors\"",
    "\"db2sql\"",
    "\"derby_jdbc_result_set\"",
    "\"dirty\"",
    "\"document\"",
    "\"each\"",
    "\"empty\"",
    "\"exclusive\"",
    "\"fn\"",
    "\"index\"",
    "\"java\"",
    "\"lcase\"",
    "\"locate\"",
    "\"lock\"",
    "\"message_locale\"",
    "\"method\"",
    "\"mode\"",
    "\"new\"",
    "\"new_table\"",
    "\"nvarchar\"",
    "\"oj\"",
    "\"off\"",
    "\"old\"",
    "\"old_table\"",
    "\"out\"",
    "\"parameter\"",
    "\"passing\"",
    "\"properties\"",
    "\"reads\"",
    "\"ref\"",
    "\"referencing\"",
    "\"rename\"",
    "\"reset\"",
    "\"result\"",
    "\"retain\"",
    "\"returning\"",
    "\"rr\"",
    "\"rs\"",
    "\"sequence\"",
    "\"sequential\"",
    "\"sets\"",
    "\"share\"",
    "\"sqlid\"",
    "\"specific\"",
    "\"sqrt\"",
    "\"stability\"",
    "\"strip\"",
    "\"style\"",
    "\"trigger\"",
    "\"ucase\"",
    "\"ur\"",
    "\"whitespace\"",
    "\"\\\"\"",
    "\"%\"",
    "\"&\"",
    "\"\\\'\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\",\"",
    "\"-\"",
    "\".\"",
    "\"/\"",
    "\":\"",
    "\"::\"",
    "\";\"",
    "\"<\"",
    "\"<=\"",
    "\"=\"",
    "\"<>\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"?\"",
    "\"_\"",
    "\"|\"",
    "\"[\"",
    "\"]\"",
    "\"||\"",
    "\"->\"",
    "<IDENTIFIER>",
    "\"K\"",
    "\"M\"",
    "\"G\"",
    "<LETTER>",
    "<DIGIT>",
    "<DELIMITED_IDENTIFIER>",
    "<EXACT_NUMERIC>",
    "<UINT>",
    "<LENGTH_MODIFIER>",
    "<STRING>",
    "<HEX_STRING>",
    "<APPROXIMATE_NUMERIC>",
    "<INTERVAL_LITERAL>",
    "<INTERVAL_STRING>",
    "<INTERVAL_QUALIFIER>",
    "<SINGLE_DATETIME_FIELD>",
    "<START_FIELD>",
    "<END_FIELD>",
    "<NON_SECOND_DATETIME_FIELD>",
    "<YEAR_MONTH_LITERAL>",
    "<DAY_TIME_LITERAL>",
    "<DAY_TIME_INTERVAL>",
    "<SECONDS_VALUE>",
    "<TIME_INTERVAL>",
  };

}
